# лаунчер программ
bindsym $mod+Shift+d exec --no-startup-id xfce4-appfinder

# rofi скрипты
bindsym $mod+d exec --no-startup-id ~/.config/i3/scripts/app/launcher.sh
bindsym $mod+m exec --no-startup-id ~/.config/i3/scripts/app/music.sh
bindsym $mod+t exec --no-startup-id ~/.config/i3/scripts/app/translate.sh

# скриншотер
bindsym $mod+s exec --no-startup-id flameshot gui

# блокировщик экрана
bindsym $mod+l exec --no-startup-id ~/.config/i3/scripts/app/lock.sh

# пипетка
bindsym --release $mod+Shift+g exec --no-startup-id ~/.config/i3/scripts/app/gpick.sh
bindsym --release $mod+g exec --no-startup-id ~/.config/i3/scripts/app/grabc.sh

# менеджер звука
bindsym $mod+v exec --no-startup-id pavucontrol

# менеджер bluetooth
bindsym $mod+b exec --no-startup-id blueman-manager

# калькулятор
bindsym $mod+k exec --no-startup-id galculator

# kitty
bindsym $mod+Shift+Return exec --no-startup-id kitty
