# системные переменные
exec --no-startup-id systemctl --user import-environment DISPLAY XAUTHORITY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE
exec --no-startup-id dbus-update-activation-environment --systemd --all
exec_always --no-startup-id sleep 2 && systemctl --user restart xdg-desktop-portal xdg-desktop-portal-gtk

# при каждом запуске
exec_always --no-startup-id ~/.config/i3/scripts/autostart/exec_always.sh

# один раз при запуске
exec --no-startup-id ~/.config/i3/scripts/autostart/exec.sh

