bar {
    height 20
    position bottom
    font pango:$font 10
#    separator_symbol "|"
    status_command i3status
    strip_workspace_numbers yes
    output $m1
    tray_output $m1

    colors {
        separator  $d
        background $bg
        statusline $fg

        focused_workspace  $b  $b  $bg
        active_workspace   $g  $g  $bg
        inactive_workspace $bg $bg $d
        urgent_workspace   $r  $r  $bg
        binding_mode       $bg $bg $y
    }

    bindsym button2 exec --no-startup-id xfce4-appfinder
    bindsym button3 exec --no-startup-id ~/.config/i3/scripts/app/launcher.sh
    bindsym button4 nop
    bindsym button5 nop
    bindsym button8 nop
    bindsym button9 workspace back_and_forth
}

