set $mode_controls Управление: ←/→ Громкость -/+, ↓/↑ Яркость -/+
mode "$mode_controls" {
    bindsym Left exec pactl set-sink-volume @DEFAULT_SINK@ -2%
    bindsym Right exec pactl set-sink-volume @DEFAULT_SINK@ +2%
    bindsym Down exec brightnessctl set 2%-
    bindsym Up exec brightnessctl set +2%
    bindsym Escape mode "default"
}
bindsym $mod+c mode "$mode_controls"

set $mode_power_profiles Профиль питания: 1-производительный, 2-сбалансированный, 3-сберегающий
mode "$mode_power_profiles" {
    bindsym 1 exec --no-startup-id powerprofilesctl set performance && notify-send "performance", mode "default"
    bindsym 2 exec --no-startup-id powerprofilesctl set balanced && notify-send "balanced", mode "default"
    bindsym 3 exec --no-startup-id powerprofilesctl set power-saver && notify-send "power saver", mode "default"
    bindsym Escape mode "default"
}
bindsym $mod+p mode "$mode_power_profiles"
