# назначение окон на рабочие столы
#assign [class="Nemo|Xed"] workspace 1
#assign [class="Vivaldi-stable|TelegramDesktop"] workspace 2
#assign [class="Alacritty"] workspace 3
#assign [class="steam"] workspace 9

# свойства окон
for_window [class="Blueman-manager|Pavucontrol|Xfce4-appfinder|Galculator"] floating enable, resize set 700 500
for_window [class="Nemo-preview-start"] resize set 700 500
for_window [floating] move position center
for_window [class="^.*"] border normal

# назначение рабочих столов на мониторы
workspace 1 output $m1
workspace 2 output $m1
workspace 3 output $m1
workspace 4 output $m1
workspace 5 output $m1
workspace 6 output $m1
workspace 7 output $m1
workspace 8 output $m1
workspace 9 output $m1
workspace 10 output $m2
